name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  run-unit-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: Test of  Unit Test tmp
        run: mvn --batch-mode --update-snapshots package

      #      - name: Unit Tests
      #        run: mvn clean package

      - name: Rename the artifact
        #run: cp target/ci-cd-test-0.0.1-SNAPSHOT.jar ci-cd-test-${{ github.sha }}.jar
        run: cp target/ci-cd-test-0.0.1-SNAPSHOT.jar ci-cd-test.jar

      - name: Save the artifact
        uses: actions/upload-artifact@v3
        with:
          name: ci-cd-test
          #          path: ci-cd-test-${{ github.sha }}.jar
          path: ci-cd-test.jar

  deploy:
    runs-on: self-hosted
    needs: run-unit-tests
    steps:
      - name: Get the artifact
        uses: actions/download-artifact@v3
        with:
          name: ci-cd-test

      - name: Wait for SSH
        run: |
          while ! nc -w5 -z ${{ secrets.SSH_HOST }} 22; do
                  sleep 1
                  echo "SSH not available..."
          done; echo "SSH ready!"

      - name: Stop App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ ! -d app ]; then
              mkdir app
            fi

      - name: deploy
        run: ls ci-cd-test*.jar
        #            pid=`ps aux | grep "[c]icd-demo.jar" | awk '{print $2}'`
        #            if [ "$pid" == "" ]; then
        #              echo "Process not found"
        #            else
        #              kill -9 $pid
        #            fi